### ISSUE TITLE
Definir padrão de linguagem e commits

### ISSUE THREAD

**Issue by reebr** [dunossauro/curriculum-online#7]
Eu vi o pull #5 e os commits que estão em inglês.
Vocês acham que é definirmos um padrão de linguagem para os commits, novas issues e documentação? Usar inglês ou português? Os commits devem referenciar o número da issue para ficar o rastreio no GitHub?

Convocando quem já se manifestou no projeto.
@dunossauro @jlugao @williangl

**Comment by jlugao** [comment]
Por mim o que for definido está bom. O importante é ficar consistente.

**Comment by williangl** [comment]
Será que ustilizando inglês conseguimos atingir um maior grupo de pessoas para nos ajudar? Sou novo com o github e não sei se há uma parcela, estatísticamente, grande de pessoas que não sabem inglês.
Gostei da ideia de utilizarmos o número da issue nos commits. Acho legal fazermos igual no trampo, começando com o número seguido da mensagem (i.e. #7 - blablabla)

**Comment by reebr** [comment]
Eu fico meio burro quando o assunto é escrever issues em inglês 😆, devo mandar altos "tacar préda no vrido" pra quem está lendo, mas dá pra arriscar com ajuda do [bing](https://www.bing.com/translator).

**Comment by williangl** [comment]
> Eu fico meio burro quando o assunto é escrever issues em inglês laughing, devo mandar altos "tacar préda no vrido" pra quem está lendo, mas dá pra arriscar com ajuda do [bing](https://www.bing.com/translator).

UASHUSAHUASHUHA sou desses tbm. Bem, como vc lembrou temos as ferramentas de tradução, creio que podemos fazer em português e outras pessoas usam o [tradutor](https://translate.google.com/), que eu, particularmente, acho muito melhor UHSUAHSAUHSUAHSUAHUASUASHUASH :kissing_heart:

**Comment by dunossauro** [comment]
Eu sinceramente usaria português. É um projeto destinado a brasileiros. Até o nome é pra brasileiros. Hauahauahaua

**Comment by williangl** [comment]
> Eu sinceramente usaria português. É um projeto destinado a brasileiros. Até o nome é pra brasileiros. Hauahauahaua

Então fechou UHSAUHASUHSUHSAUHSUHA
